/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LezSideDrawer {
        "close": () => Promise<void>;
        "isOpen": boolean;
        "open": () => Promise<void>;
        "panelTitle": string;
        "toggle": () => Promise<void>;
    }
}
declare global {
    interface HTMLLezSideDrawerElement extends Components.LezSideDrawer, HTMLStencilElement {
    }
    var HTMLLezSideDrawerElement: {
        prototype: HTMLLezSideDrawerElement;
        new (): HTMLLezSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "lez-side-drawer": HTMLLezSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface LezSideDrawer {
        "isOpen"?: boolean;
        "panelTitle"?: string;
    }
    interface IntrinsicElements {
        "lez-side-drawer": LezSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lez-side-drawer": LocalJSX.LezSideDrawer & JSXBase.HTMLAttributes<HTMLLezSideDrawerElement>;
        }
    }
}
